#!/bin/bash

# Split the PATH environment variable by the path separator and count the number of directories
num_path_dirs=$(echo $PATH | tr ':' '\n' | wc -l)

echo "The number of directories in the PATH is: $num_path_dirs"

